"""Decomposition Generator agent.

Stage 5 of the MVP roadmap. Generates ``num_candidates`` candidate decompositions,
one per strategy, rotating through the strategy list when ``num_candidates`` is
larger than the strategy count.

Each candidate is generated by an independent LLM call so failures (bad JSON,
schema violation) can be retried in isolation without re-running the full batch.
"""
from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from agentic_decomposer.agents.base import AgentResult, BaseAgent
from agentic_decomposer.artifacts.validators import ValidationError, validate
from agentic_decomposer.helpers import LLMOutputError, extract_json_object
from agentic_decomposer.llm.client import LLMClient, LLMConfig
from agentic_decomposer.paths import PROMPTS_DIR
from agentic_decomposer.runs import write_json


_STRATEGIES = ("dependency_first", "domain_first", "balanced")

_COMMON_PROMPT  = PROMPTS_DIR / "generator_common.md"
_STRATEGY_FILES = {
    "dependency_first": PROMPTS_DIR / "generator_dependency_first.md",
    "domain_first":     PROMPTS_DIR / "generator_domain_first.md",
    "balanced":         PROMPTS_DIR / "generator_balanced.md",
}

_MAX_RETRIES_PER_CANDIDATE = 2


@dataclass
class _CandidateResult:
    candidate: dict
    tokens: int
    attempts: int
    error: str | None


class DecompositionGeneratorAgent(BaseAgent):
    name = "decomposition_generator"

    def _run(self, evidence_pack: dict | None = None,
             domain_model: dict | None = None, **_: Any) -> AgentResult:
        if not evidence_pack:
            raise ValueError("DecompositionGeneratorAgent requires evidence_pack")
        domain_model = domain_model or {
            "business_capabilities": [],
            "class_capability_matrix": [],
        }

        llm = LLMClient(LLMConfig(
            model=self.config.model,
            seed=self.config.seed,
            log_path=self.layout.llm_calls_log_path,
        ))

        candidates: list[dict] = []
        total_tokens = 0
        schema_validation: list[dict] = []
        common_template = _COMMON_PROMPT.read_text(encoding="utf-8")

        for idx in range(self.config.num_candidates):
            strategy = _STRATEGIES[idx % len(_STRATEGIES)]
            cand_id = f"CAND_{idx + 1:03d}"
            result = self._generate_one(
                cand_id=cand_id,
                index=idx + 1,
                strategy=strategy,
                evidence=evidence_pack,
                domain=domain_model,
                llm=llm,
                common_template=common_template,
            )
            schema_validation.append({
                "candidate_id": cand_id,
                "strategy":     strategy,
                "attempts":     result.attempts,
                "ok":           result.error is None,
                "error":        result.error,
            })
            if result.error is None:
                candidates.append(result.candidate)
            total_tokens += result.tokens

        if not candidates:
            raise RuntimeError(
                "DecompositionGenerator produced no schema-valid candidates. "
                "See schema_validation.json for per-candidate errors."
            )

        payload = {
            "system": self.config.system,
            "candidates": candidates,
            "metadata": {
                "generated_at_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
                "model": self.config.model,
                "tokens_used": int(total_tokens),
                "stub": False,
            },
        }
        validate(payload, "candidate_decomposition")
        write_json(self.layout.candidates_path, payload)
        write_json(self.layout.candidates_validation_path, {
            "system": self.config.system,
            "candidates": schema_validation,
        })
        return AgentResult(
            name=self.name, output=payload,
            output_path=str(self.layout.candidates_path),
            tokens_used=total_tokens,
        )

    # ------------------------------------------------------------------
    def _generate_one(
        self,
        *,
        cand_id: str,
        index: int,
        strategy: str,
        evidence: dict,
        domain: dict,
        llm: LLMClient,
        common_template: str,
    ) -> _CandidateResult:
        directive = _STRATEGY_FILES[strategy].read_text(encoding="utf-8")
        max_services = self.config.constraints.max_services or "no maximum"
        min_services = self.config.constraints.min_services

        prompt = (
            common_template
            .replace("<<SYSTEM>>", self.config.system)
            .replace("<<STRATEGY>>", strategy)
            .replace("<<STRATEGY_DIRECTIVE>>", directive.strip())
            .replace("<<INDEX>>", f"{index:03d}")
            .replace("<<MIN_SERVICES>>", str(min_services))
            .replace("<<MAX_SERVICES>>", str(max_services))
            .replace("<<COMPONENTS_BLOCK>>", _format_components(evidence))
            .replace("<<ENTITIES_BLOCK>>",   _format_entities(evidence))
            .replace("<<EDGES_BLOCK>>",      _format_edges(evidence))
            .replace("<<ENDPOINTS_BLOCK>>",  _format_endpoints(evidence))
            .replace("<<CAPABILITIES_BLOCK>>", _format_capabilities(domain))
            .replace("<<MATRIX_BLOCK>>",     _format_matrix(domain))
            .replace("<<CLASSES_BLOCK>>",    _format_classes(evidence))
        )

        tokens = 0
        last_error: str | None = None
        for attempt in range(1, _MAX_RETRIES_PER_CANDIDATE + 1):
            self.logger.info("generator.start candidate=%s strategy=%s attempt=%d",
                             cand_id, strategy, attempt)
            try:
                response = llm.complete(
                    system="You are a software architect that outputs strict JSON.",
                    user=prompt if attempt == 1 else prompt + _RETRY_SUFFIX.format(error=last_error),
                )
            except Exception as exc:  # network / provider failure
                last_error = f"llm_call_failed: {exc}"
                continue
            tokens += response.total_tokens or 0
            try:
                raw = extract_json_object(response.text)
            except LLMOutputError as exc:
                last_error = f"json_parse_failed: {exc}"
                continue

            candidate = self._normalise_candidate(raw, cand_id, strategy, evidence)
            try:
                validate({"system": self.config.system, "candidates": [candidate]},
                         "candidate_decomposition")
            except ValidationError as exc:
                last_error = f"schema_validation_failed: {exc.messages[:3]}"
                continue
            return _CandidateResult(candidate=candidate, tokens=tokens,
                                    attempts=attempt, error=None)

        return _CandidateResult(candidate={}, tokens=tokens,
                                attempts=_MAX_RETRIES_PER_CANDIDATE,
                                error=last_error or "unknown_error")

    # ------------------------------------------------------------------
    def _normalise_candidate(
        self,
        raw: dict,
        cand_id: str,
        strategy: str,
        evidence: dict,
    ) -> dict:
        known_classes = {c["name"] for c in evidence.get("classes", [])}
        services_raw = raw.get("services") or []

        # Normalise each service
        services: list[dict] = []
        seen_classes: set[str] = set()
        for svc in services_raw:
            name = str(svc.get("name") or "UnnamedService").strip()
            class_ids: list[dict] = []
            for cls in svc.get("classes", []):
                cid = cls.get("id") if isinstance(cls, dict) else str(cls)
                cid = _simple(cid)
                if not cid or cid in seen_classes:
                    continue
                if known_classes and cid not in known_classes:
                    continue
                class_ids.append({"id": cid})
                seen_classes.add(cid)
            if not class_ids:
                continue
            services.append({
                "name": name,
                "classes": class_ids,
                "responsibilities": [str(r) for r in (svc.get("responsibilities") or [])
                                     if isinstance(r, str)] or ["(no responsibility recorded)"],
                "dependencies": [str(d) for d in (svc.get("dependencies") or [])
                                 if isinstance(d, str)],
                "evidence_refs": [str(e) for e in (svc.get("evidence_refs") or [])
                                  if isinstance(e, str)],
            })

        # Assign any leftover known classes to a catch-all UnassignedService so
        # the candidate stays schema-valid for the constraint
        # "each_class_assigned_once" + "allow_unassigned_classes=false".
        leftover = sorted(known_classes - seen_classes)
        if leftover and not self.config.constraints.allow_unassigned_classes:
            services.append({
                "name": "UnassignedService",
                "classes": [{"id": c} for c in leftover],
                "responsibilities": [
                    "Catch-all service for classes the generator did not place.",
                ],
                "dependencies": [],
                "evidence_refs": [],
            })

        # Dependency hygiene: drop dependency references to services that do
        # not exist in this candidate.
        service_names = {s["name"] for s in services}
        for svc in services:
            svc["dependencies"] = [d for d in svc["dependencies"] if d in service_names and d != svc["name"]]

        return {
            "candidate_id":         cand_id,
            "strategy":             strategy,
            "services":             services,
            "rationale":            str(raw.get("rationale") or "(no rationale)"),
            "parent_candidate_id":  None,
            "refinement_round":     0,
        }


_RETRY_SUFFIX = (
    "\n\n---\nYour previous response failed validation: {error}\n"
    "Reply with ONLY the corrected JSON object — no prose."
)


# ----------------------------------------------------------------------
# Compact context formatters
# ----------------------------------------------------------------------

def _format_components(ev: dict) -> str:
    rows = []
    for c in ev.get("components", []):
        rows.append(
            f"- {c['id']} | {c['name']} | type={c.get('type')} | "
            f"classes={', '.join(c.get('classes', [])[:30])}"
        )
    return "\n".join(rows) or "(none)"


def _format_entities(ev: dict) -> str:
    rows = []
    for e in ev.get("persistence_entities", []):
        rows.append(
            f"- {e['entity']} | repo={e.get('repository')} | "
            f"tables={', '.join(e.get('tables') or [])}"
        )
    return "\n".join(rows) or "(none)"


def _format_edges(ev: dict) -> str:
    edges = sorted(ev.get("dependency_edges", []),
                   key=lambda e: -int(e.get("weight", 1)))
    rows = []
    for e in edges[:200]:
        rows.append(
            f"- {e['id']} | {e['source']} --{e['type']}({e.get('weight', 1)})--> {e['target']}"
        )
    return "\n".join(rows) or "(none)"


def _format_endpoints(ev: dict) -> str:
    rows = []
    for ep in ev.get("api_endpoints", [])[:80]:
        rows.append(
            f"- {ep['id']} | {ep['method']} {ep['path']} → {ep['handler_class']}"
        )
    return "\n".join(rows) or "(none)"


def _format_capabilities(dm: dict) -> str:
    rows = []
    for cap in dm.get("business_capabilities", []):
        cls = ", ".join(c["class"] for c in (cap.get("related_classes") or [])[:30])
        rows.append(f"- {cap['id']} | {cap['name']}: {cap.get('description') or ''} | classes=[{cls}]")
    return "\n".join(rows) or "(no capabilities; domain agent ablated)"


def _format_matrix(dm: dict) -> str:
    rows = []
    for r in dm.get("class_capability_matrix", []):
        rows.append(
            f"- {r['class']} → {r['capability_id']} (conf={r.get('confidence')})"
        )
    return "\n".join(rows) or "(empty)"


def _format_classes(ev: dict) -> str:
    rows = []
    for c in ev.get("classes", []):
        stereotypes = ",".join(c.get("stereotypes") or []) or "-"
        rows.append(f"- {c.get('id', '')} | {c['name']} | {c.get('package', '')} | {stereotypes}")
    return "\n".join(rows)


def _simple(name: object) -> str:
    if isinstance(name, dict):
        return str(name.get("id") or name.get("name") or "").rsplit(".", 1)[-1]
    return str(name or "").rsplit(".", 1)[-1]
